name: Deploy to hosting via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Clean build folder
        run: rm -rf build

      - name: Build React App
        run: npm run build

      - name: Move API catalog
        run: mv api build/api

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan oski1993.ssh.dhosting.pl >> ~/.ssh/known_hosts

      - name: Deploy to Server using SCP
        env:
          REMOTE_PATH: /home/klient.dhosting.pl/oski1993/przepisy.dkonto.pl/public_html
          USERNAME: oski1993
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$PASSWORD" scp -r -o StrictHostKeyChecking=no build/. oski1993@oski1993.ssh.dhosting.pl:/home/klient.dhosting.pl/oski1993/przepisy.dkonto.pl/public_html
